# Generated by Django 5.1.3 on 2025-04-25 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_records', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingrecord',
            name='cooking_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooking_records.cookingcategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='cookingrecord',
            name='cooking_easiness',
            field=models.IntegerField(choices=[(0, '簡単'), (1, '普通'), (2, '手間がかかる')], default=1, verbose_name='調理の手軽さ'),
        ),
        migrations.AlterField(
            model_name='cookingrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='cookingrecord',
            name='is_favorite',
            field=models.IntegerField(default=0, verbose_name='お気に入り'),
        ),
        migrations.AlterField(
            model_name='cookingrecord',
            name='memo',
            field=models.CharField(blank=True, max_length=300, verbose_name='メモ'),
        ),
        migrations.CreateModel(
            name='CookingRecordRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_records.cookingrecord')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
