# Generated by Django 5.1.3 on 2025-04-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sharegroup_invitation_alter_user_share_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
