# Generated by Django 5.1.3 on 2025-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_images/'),
        ),
    ]
